# Generated by Django 5.2.11 on 2026-02-21 11:54

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0134_owner'),
        ('ipam', '0086_gfk_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('dns_server1', models.CharField(blank=True, default='', max_length=255)),
                ('dns_server2', models.CharField(blank=True, default='', max_length=255)),
                ('dns_server3', models.CharField(blank=True, default='', max_length=255)),
                ('perform_dns_lookup', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plugin Settings',
                'verbose_name_plural': 'Plugin Settings',
            },
        ),
        migrations.CreateModel(
            name='PingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('is_reachable', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('dns_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ping_result', to='ipam.ipaddress')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Ping Result',
                'verbose_name_plural': 'Ping Results',
                'ordering': ['-last_checked'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubnetScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('total_hosts', models.IntegerField(default=0)),
                ('hosts_up', models.IntegerField(default=0)),
                ('hosts_down', models.IntegerField(default=0)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('prefix', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_result', to='ipam.prefix')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Subnet Scan Result',
                'verbose_name_plural': 'Subnet Scan Results',
                'ordering': ['-last_scanned'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
