# Generated by Django 5.2.11 on 2026-02-21 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0086_gfk_indexes'),
        ('netbox_ping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginsettings',
            name='auto_discover_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pluginsettings',
            name='auto_discover_interval',
            field=models.IntegerField(default=1440),
        ),
        migrations.AddField(
            model_name='pluginsettings',
            name='auto_scan_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pluginsettings',
            name='auto_scan_interval',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='pluginsettings',
            name='max_prefix_size',
            field=models.IntegerField(default=24),
        ),
        migrations.CreateModel(
            name='PrefixSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('auto_scan_enabled', models.BooleanField(default=True)),
                ('scan_interval', models.IntegerField(default=0)),
                ('auto_discover_enabled', models.BooleanField(default=False)),
                ('discover_interval', models.IntegerField(default=0)),
                ('prefix', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ping_schedule', to='ipam.prefix')),
            ],
            options={
                'verbose_name': 'Prefix Schedule',
                'verbose_name_plural': 'Prefix Schedules',
            },
        ),
    ]
