# Generated by Django 5.2.11 on 2026-02-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_ping', '0002_pluginsettings_auto_discover_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefixschedule',
            name='auto_discover_enabled',
        ),
        migrations.RemoveField(
            model_name='prefixschedule',
            name='auto_scan_enabled',
        ),
        migrations.AddField(
            model_name='prefixschedule',
            name='discover_mode',
            field=models.CharField(default='follow_global', max_length=20),
        ),
        migrations.AddField(
            model_name='prefixschedule',
            name='scan_mode',
            field=models.CharField(default='follow_global', max_length=20),
        ),
        migrations.AlterField(
            model_name='prefixschedule',
            name='discover_interval',
            field=models.IntegerField(default=1440),
        ),
        migrations.AlterField(
            model_name='prefixschedule',
            name='scan_interval',
            field=models.IntegerField(default=60),
        ),
    ]
