# Generated by Django 5.2.11 on 2026-02-27 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_ping', '0010_email_notifications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dnshistory',
            new_name='netbox_ping_ip_addr_ddf95e_idx',
            old_name='netbox_ping_ip_address_c85a9e_idx',
        ),
        migrations.RenameIndex(
            model_name='pinghistory',
            new_name='netbox_ping_ip_addr_553995_idx',
            old_name='netbox_ping_ip_addr_b3f4e7_idx',
        ),
        migrations.RenameIndex(
            model_name='scanevent',
            new_name='netbox_ping_digest__57f0af_idx',
            old_name='netbox_ping_digest_sent_idx',
        ),
    ]
