# Generated by Django 5.2.11 on 2026-02-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_ping', '0011_rename_netbox_ping_ip_address_c85a9e_idx_netbox_ping_ip_addr_ddf95e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingresult',
            name='consecutive_down_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pingresult',
            name='is_stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pluginsettings',
            name='stale_days_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pluginsettings',
            name='stale_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pluginsettings',
            name='stale_remove_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='pluginsettings',
            name='stale_remove_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pluginsettings',
            name='stale_scans_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prefixschedule',
            name='stale_mode',
            field=models.CharField(default='follow_global', max_length=20),
        ),
        migrations.AddField(
            model_name='subnetscanresult',
            name='hosts_stale',
            field=models.IntegerField(default=0),
        ),
    ]
