# Generated by Django 5.2.12 on 2026-04-18 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0086_gfk_indexes'),
        ('netbox_ping', '0017_pluginsettings_ping_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pingresult',
            name='uptime_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UptimeReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('reset_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('previous_reset_at', models.DateTimeField(blank=True, null=True)),
                ('ping_count_at_reset', models.IntegerField(default=0)),
                ('uptime_24h_at_reset', models.FloatField(blank=True, null=True)),
                ('uptime_7d_at_reset', models.FloatField(blank=True, null=True)),
                ('uptime_30d_at_reset', models.FloatField(blank=True, null=True)),
                ('uptime_all_time_at_reset', models.FloatField(blank=True, null=True)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_resets', to='ipam.ipaddress')),
                ('reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='netbox_ping_uptime_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uptime Reset',
                'verbose_name_plural': 'Uptime Resets',
                'ordering': ['-reset_at'],
                'indexes': [models.Index(fields=['ip_address', '-reset_at'], name='netbox_ping_ip_addr_1520dc_idx')],
            },
        ),
    ]
