# Generated by Django 5.2.12 on 2026-05-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_ping', '0018_pingresult_uptime_reset_at_uptimereset'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginsettings',
            name='discover_inherit_vrf_from_prefix',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pluginsettings',
            name='sla_excellent_threshold',
            field=models.FloatField(default=99.9),
        ),
        migrations.AddField(
            model_name='pluginsettings',
            name='sla_good_threshold',
            field=models.FloatField(default=99.0),
        ),
        migrations.AddField(
            model_name='pluginsettings',
            name='sla_warning_threshold',
            field=models.FloatField(default=95.0),
        ),
    ]
