# Generated by Django 6.0.5 on 2026-06-18 10:45

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    # Pin the NetBox 4.5.0 leaf nodes (same as 0001_initial) rather than the
    # 4.6 nodes makemigrations emitted in the dev container. These operations
    # only require ipam.VRF (the OneToOne FK) and extras.TaggedItem (tags), both
    # of which exist well before these nodes — so the migration applies on every
    # NetBox from the declared floor (4.5.0) through current.
    dependencies = [
        ('extras', '0134_owner'),
        ('ipam', '0086_gfk_indexes'),
        ('netbox_ping', '0019_pluginsettings_discover_inherit_vrf_from_prefix_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefixschedule',
            options={'ordering': ['prefix']},
        ),
        migrations.AddField(
            model_name='prefixschedule',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prefixschedule',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AddField(
            model_name='prefixschedule',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='prefixschedule',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.CreateModel(
            name='VrfPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('scan_mode', models.CharField(default='follow_global', max_length=20)),
                ('discover_mode', models.CharField(default='follow_global', max_length=20)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('vrf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ping_policy', to='ipam.vrf')),
            ],
            options={
                'verbose_name': 'VRF Policy',
                'verbose_name_plural': 'VRF Policies',
                'ordering': ['vrf__name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
